sudo: false
language: node_js
node_js: 6
env:
  global:
  - secure: GxQwdMcMY9CVX1N1y+hIxsmuuu1fCsRy29ajl2bWUJvhJzXoA9XBxuPgupc9BdQR4BkE6PxFmwpwKzFcBl0reYNaDBCVAf2g/ByCOUdXwpZ+Er0iSfK20bYcEXXBe5D8BJnZIVqCavuUILk424AJvxVjpXZelE9noGVLEPeT6V4=
  - secure: JbIvIggLmYe3yO5TR+Cgpe/eIkGjifPvHIk3JKewkY8Sk/maSDC3CiNB3w5BByt2PHr9gA/d83JbyJ1F19N4tRXaA39RQq6GAb0ljFoujwgf0chY0ELCPkdxbiP7St8i3dqNSWECaQNbhgbzSzOV0U2vfgtv1lmT8yQChrAEnEU=
  - secure: SmQ+YNersmisfZhj1IRFLGdWnSs6Fas9BNl4J6DI4BRbv/EKU07lZqi5D7reDcEo3rinxXES9hksR+/oUC73/OHE9d19TEh0O20uaq9rciLtOrgQAHVfj/k38GtG8ZQE7DpKe/kesSreBagbebMk7AIYG0hf981qebt5qs8B8dI=
cache:
  apt: true
  yarn: true
  directories:
  - website/.lanyon
install: npm install
script: npm run lint && npm run test
before_cache:
- rm -f ./node_modules/.bin/which
before_deploy: .lanyon/bin/install
deploy:
  skip_cleanup: true
  provider: script
  script: website/.lanyon/bin/deploy
  on:
    branch: master
    condition: $TRAVIS_OS_NAME = linux
notifications:
  slack:
    secure: Vx2sPpEgzU3LWCfcfRleeHIVKfhAxC9k0DO3hKSOTv4fjn68yS10AIQUjEpkg5CPmckAikNgKeLjHMdnFZbysjRT/aRqe3/YNnStmWtyFZj+C3hboKQ85POQbDU+D3GFaO0rn3lXMMXB4AOahpkaVnABSXcXlXKDYKfDmn+5Vh8=
